### ISSUE TITLE
What to do with coins

### ISSUE THREAD

**Issue by Nagol12344** [MCPE-ADD-ONS/Some-weird-awards#5]
Hello,

I am adding coins to the mod and do not know what to do with them. If you have a idea please put it here,

Thanks 
@Nagol12344 Part of the @MCPE-ADD-ONS/awards Team

**Comment by Gamediamond3757** [comment]
you could buy stuff with it like more stuff you add to the mod

**Comment by Nagol12344** [comment]
how would i get a shop into the mod?

**Comment by Gamediamond3757** [comment]
idk

**Comment by Nagol12344** [comment]
-_-

**Comment by Gamediamond3757** [comment]
nothing
